name: ruleguard

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: stable
      args:
        required: false
        type: string
        default: ""
      working-directory:
        required: false
        type: string
        default: "."

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          working-directory: ${{ inputs.working-directory }}
          repository: dgryski/semgrep-go
          path: rules
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          working-directory: ${{ inputs.working-directory }}
          go-version: ${{ inputs.go-version }}
      - name: ruleguard
        working-directory: ${{ inputs.working-directory }}
        run: |
          # needs to be outside of the workspace for some reason
          mv rules ../
          go install github.com/quasilyte/go-ruleguard/cmd/ruleguard@latest
          go get -u github.com/quasilyte/go-ruleguard/dsl@latest
          ruleguard -c=0 -rules ../rules/ruleguard.rules.go ${{ inputs.args }} ./...
